# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SF_Inke' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SF_Inke
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'YYKit', '~> 1.0.7'
pod 'Masonry', '~> 1.0.1'
pod 'LFLiveKit', '~> 2.2.4.3'
end
